---
title: "MAT 350: Matrices, Matrix Arithmetic, and Operations"
author: Dr. Gilbert
format: 
  revealjs:
    smaller: true
date: today
date-format: long
theme: serif
incremental: true
---

```{r global-options, include=FALSE}
library(tidyverse)
library(reticulate)

theme_set(theme_bw(base_size = 20))
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

```{css}
code.sourceCode {
  font-size: 1.3em;
  /* or try font-size: xx-large; */
}

a {
  color: purple;
}

a:link {
  color: purple;
}

a:visited {
  color: purple;
}
```

## Matrices (Definition)

. . .

A **matrix** is a rectangular array of numbers arranged in rows and columns. 

+ Matrices are used to represent and solve systems of linear equations, perform transformations, and model various real-world systems in science and engineering.

. . .

***Note*:** In MAT350, we'll consider matrices whose entries are real numbers, although this restriction is not generally required.

## Dimensions of Matrices

. . .

The **dimension** (or size) of a matrix is described as $m \times n$ (read: "$m$ by $n$"), where $m$ is the number of rows and $n$ is the number of columns.

. . . 

**Example:** The matrix $A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}$ is a $2 \times 3$ matrix.

. . .

**Example:** Find the dimensions of each of the following matrices

. . .

$$B = \begin{bmatrix} 2 & 8\\ -3 & 1\\ -5 & -2\\ 0 & 7\end{bmatrix}~~~~~~C = \begin{bmatrix} -2 & 0\\ 0 & 0\end{bmatrix}~~~~~~D = \begin{bmatrix} -9\\ 0\\ 1\\ 4\\ -3\end{bmatrix}$$

## Transposing Matrices

. . .

Similar to vectors, we can *transpose* a matrix. 

+ If the matrix $A$ is an $m\times n$ matrix, then the matrix $A^T$ is an $n\times m$ matrix whose rows are the columns of the matrix $A$. 

    + The first row of the matrix $A$ is the first column of the matrix $A^T$ and so on.

. . .

**Example:** Determine the *transpose* for each of the following matrices.

::::{.columns}

:::{.column width=50%}

+ $A = \begin{bmatrix} 1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix}$
+ $B = \begin{bmatrix} 1 & 4 & -1\\ 2 & 5 & 0\\ 3 & 0 & 6\end{bmatrix}$.

:::

::::

## Transposing Matrices

:::{.nonincremental}

Similar to vectors, we can *transpose* a matrix. 

+ If the matrix $A$ is an $m\times n$ matrix, then the matrix $A^T$ is an $n\times m$ matrix whose rows are the columns of the matrix $A$. 

    + The first row of the matrix $A$ is the first column of the matrix $A^T$ and so on.

:::

**Example:** Determine the *transpose* for each of the following matrices.

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ $A = \begin{bmatrix} 1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix}$
+ $B = \begin{bmatrix} 1 & 4 & -1\\ 2 & 5 & 0\\ 3 & 0 & 6\end{bmatrix}$.

:::

::::

::::{.column width=50%}

$$A^T = \begin{bmatrix} 1 & 4\\ 2 & 5\\ 3 & 6\end{bmatrix}$$

::::

:::::

. . .

**Example:** If the matrix $A$ is a $5\times 7$ matrix, then what are the dimensions of the matrix $A^T$?

## Scalar Multiplication

. . .

<div style="font-size:16pt">

Consider the matrix $A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}$ and a scalar $c$. 

</div>

. . .

::::{.columns}

:::{.column width=50%}

<div style="font-size:16pt">

The product $cA$ is obtained by multiplying every element of $A$ by the scalar $c$. That is,

</div>

:::

:::{.column width=50%}

:::

::::

## Scalar Multiplication

<div style="font-size:16pt">

Consider the matrix $A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}$ and a scalar $c$. 

</div>

::::{.columns}

:::{.column width=50%}

<div style="font-size:16pt">

The product $cA$ is obtained by multiplying every element of $A$ by the scalar $c$. That is,

</div>

:::

:::{.column width=50%}

<div style="font-size:16pt">

$$cA = \begin{bmatrix} ca_{11} & ca_{12} & \cdots & ca_{1n}\\
ca_{21} & ca_{22} & \cdots & ca_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
ca_{m1} & ca_{m2} & \cdots & ca_{mn}\end{bmatrix}$$

</div>

:::

::::

. . .

<div style="font-size:16pt">

**Example:** Consider the matrix $A = \begin{bmatrix} 5 & -2 & 0 & 11 & 7\\
-3 & 1 & 1 & 4 & 0\\
0 & 0 & 2 & 1 & -5\end{bmatrix}$. Compute the product $-2A$.

</div>

. . . 

<div style="font-size:16pt">

$$\color{red}{-2}A = \begin{bmatrix} \color{red}{-2}\left(5\right) & \color{red}{-2}\left(-2\right) & \color{red}{-2}\left(0\right) & \color{red}{-2}\left(11\right) & \color{red}{-2}\left(7\right)\\ \color{red}{-2}\left(-3\right) & \color{red}{-2}\left(1\right) & \color{red}{-2}\left(1\right) & \color{red}{-2}\left(4\right) & \color{red}{-2}\left(0\right)\\ \color{red}{-2}\left(0\right) & \color{red}{-2}\left(0\right) & \color{red}{-2}\left(2\right) & \color{red}{-2}\left(1\right) & \color{red}{-2}\left(-5\right)\end{bmatrix}$$

</div>

## Scalar Multiplication

<div style="font-size:16pt">

Consider the matrix $A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots &  &  \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}$ and a scalar $c$. 

</div>

::::{.columns}

:::{.column width=50%}

<div style="font-size:16pt">

The product $cA$ is obtained by multiplying every element of $A$ by the scalar $c$. That is,

</div>

:::

:::{.column width=50%}

<div style="font-size:16pt">

$$cA = \begin{bmatrix} ca_{11} & ca_{12} & \cdots & ca_{1n}\\
ca_{21} & ca_{22} & \cdots & ca_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
ca_{m1} & ca_{m2} & \cdots & ca_{mn}\end{bmatrix}$$

</div>

:::

::::

<div style="font-size:16pt">

**Example:** Consider the matrix $A = \begin{bmatrix} 5 & -2 & 0 & 11 & 7\\
-3 & 1 & 1 & 4 & 0\\
0 & 0 & 2 & 1 & -5\end{bmatrix}$. Compute the product $-2A$.

</div>

<div style="font-size:16pt">

$$-2A = \begin{bmatrix} -10 & 4 & 0 & -22 & -14\\ 6 & -2 & -2 & -8 & 0\\ 0 & 0 & -4 & -2 & 10\end{bmatrix}$$

</div>

## Matrix Addition and Subtraction

. . .

Like vectors, matrices can be added or subtracted if they have the same dimensions. 

. . .

Addition and subtraction are performed element-wise. That is, if

. . .

$$A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}~~~~~\text{and}~~~~~B = \begin{bmatrix} b_{11} & b_{12} & \cdots & b_{1n}\\
b_{21} & b_{22} & \cdots & b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
b_{m1} & b_{m2} & \cdots & b_{mn}\end{bmatrix}$$

. . .

then

$$A + B = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + B_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\end{bmatrix}$$

## Matrix Addition and Subtraction

$$A + B = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\
a_{21} + b_{21} & a_{22} + B_{22} & \cdots & a_{2n} + b_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\end{bmatrix}$$

. . .

**Example:** Let $A = \begin{bmatrix}
1 & -2 & 0 \\
0 & 7 & -1
\end{bmatrix}$
and $B = \begin{bmatrix}
5 & -3 & 1 \\
-1 & 2 & 8
\end{bmatrix}$, then compute

+ $A + B$
+ $A - B$, note that $A - B$ is the same as $A + (-1B)$
+ $B - A$

. . .

$$A - B = \begin{bmatrix}1 - 5 & -2 - \left(-3\right) & 0 - 1\\ 0 - \left(-1\right) & 7 - 2 & -1 - 8\end{bmatrix} = \begin{bmatrix} -4 & 1 & -1\\ 1 & 5 & -9\end{bmatrix}$$

## Matrix Multiplication

. . .

Matrix multiplication is not done element-wise, instead it is based on row-by-column dot products. 

. . .

Given matrices $A$ and $B$, the $ij^{\text{th}}$ entry (the entry in row $i$ and column $j$) of the matrix product $AB$ is given by the dot product between row $i$ of matrix $A$ and column $j$ of matrix $B$.

. . .

**Requirements and Results:** Because the matrix product $AB$ consists of dot products between rows of $A$ and columns of $B$, then

+ the number of columns in the matrix $A$ must match the number of rows in the matrix $B$.
+ the matrix $AB$ has the same number of rows as the matrix $A$ but the same number of columns as the matrix $B$.

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

. . .

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ 3 & 1 & 1\end{bmatrix}$ and $B=\begin{bmatrix} 1 & 4\\ 0 & -2\\ 3 & 0\end{bmatrix}$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} \color{red}{1} & \color{red}{0} & \color{red}{-2}\\ 3 & 1 & 1\end{bmatrix}$ and $B=\begin{bmatrix} \color{red}{1} & 4\\ \color{red}{0} & -2\\ \color{red}{3} & 0\end{bmatrix}$

. . .

$$AB = \begin{bmatrix} \color{red}{1\left(1\right) + 0\left(0\right) + \left(-2\right)\left(3\right)} & ~~~~~~~~~~~~~~~~~~ \\ & \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} \color{red}{1} & \color{red}{0} & \color{red}{-2}\\ 3 & 1 & 1\end{bmatrix}$ and $B=\begin{bmatrix} 1 & \color{red}{4}\\ 0 & \color{red}{-2}\\ 3 & \color{red}{0}\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & ~~~~~~~~~~~~~~~~~~ \\ & \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} \color{red}{1} & \color{red}{0} & \color{red}{-2}\\ 3 & 1 & 1\end{bmatrix}$ and $B=\begin{bmatrix} 1 & \color{red}{4}\\ 0 & \color{red}{-2}\\ 3 & \color{red}{0}\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & \color{red}{1\left(4\right) + 0\left(-2\right) + \left(-2\right)\left(0\right)} \\ & \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ \color{red}{3} & \color{red}{1} & \color{red}{1}\end{bmatrix}$ and $B=\begin{bmatrix} \color{red}{1} & 4\\ \color{red}{0} & -2\\ \color{red}{3} & 0\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & 4 \\  & \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ \color{red}{3} & \color{red}{1} & \color{red}{1}\end{bmatrix}$ and $B=\begin{bmatrix} \color{red}{1} & 4\\ \color{red}{0} & -2\\ \color{red}{3} & 0\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & 4 \\ \color{red}{3\left(1\right) + 1\left(0\right) + 1\left(3\right)} & \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ \color{red}{3} & \color{red}{1} & \color{red}{1}\end{bmatrix}$ and $B=\begin{bmatrix} 1 & \color{red}{4}\\ 0 & \color{red}{-2}\\ 3 & \color{red}{0}\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & 4 \\ 6 &  \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ \color{red}{3} & \color{red}{1} & \color{red}{1}\end{bmatrix}$ and $B=\begin{bmatrix} 1 & \color{red}{4}\\ 0 & \color{red}{-2}\\ 3 & \color{red}{0}\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & 4 \\ 6 & \color{red}{3\left(4\right) + 1\left(-2\right) + 1\left(0\right)} \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

Compute $AB$ where $A = \begin{bmatrix} 1 & 0 & -2\\ 3 & 1 & 1\end{bmatrix}$ and $B=\begin{bmatrix} 1 & 4\\ 0 & -2\\ 3 & 0\end{bmatrix}$

$$AB = \begin{bmatrix} -5 & 4 \\ 6 & 10 \end{bmatrix}$$

## Matrix Multiplication

**Example:** Given the matrices below, compute the matrix products if they are defined. If the matrix product is not defined, describe why.

+ Compute $AB$ where $A = \begin{bmatrix} 3 & -2\\ 1 & 6\end{bmatrix}$ and $B = \begin{bmatrix} 0 & 3\\ -2 & 1\end{bmatrix}$
+ Compute $BA$ for the matrices $A$ and $B$ defined in the previous part.
+ Compute $AB$ where $A = \begin{bmatrix} -1 & 0\\ 3 & -1\end{bmatrix}$ and $B = \begin{bmatrix} 1 & -1\\ 2 & 0\\ -3 & 5\end{bmatrix}$
+ Compute $BA$ for the matrices $A$ and $B$ defined in the previous part.

## Matrix-Vector Multiplication

. . .

We can treat vectors as $n\times 1$ matrices, so multiplying vecrors by matrices is also possible (and often very useful!).

. . .

**Example:** Compute the product $A\vec{v}$ where $A = \begin{bmatrix} 1 & 0 & -1\\ 0 & 2 & 3\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 2\\ -1\\ 3\end{bmatrix}$

## Matrix-Vector Multiplication

We can treat vectors as $n\times 1$ matrices, so multiplying vectors by matrices is also possible (and often very useful!).

**Example:** Compute the product $A\vec{v}$ where $A = \begin{bmatrix} \color{red}{1} & \color{red}{0} & \color{red}{-1}\\ 0 & 2 & 3\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} \color{red}{2}\\ \color{red}{-1}\\ \color{red}{3}\end{bmatrix}$

. . .

$$A\vec{v} = \begin{bmatrix} \color{red}{1\left(2\right) + 0\left(-1\right) + \left(-1\right)\left(3\right)}\\ ~~~~~~~ \end{bmatrix}$$

## Matrix-Vector Multiplication

We can treat vectors as $n\times 1$ matrices, so multiplying vectors by matrices is also possible (and often very useful!).

**Example:** Compute the product $A\vec{v}$ where $A = \begin{bmatrix} 1 & 0 & -1\\ \color{red}{0} & \color{red}{2} & \color{red}{3}\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} \color{red}{2}\\ \color{red}{-1}\\ \color{red}{3}\end{bmatrix}$

$$A\vec{v} = \begin{bmatrix} -1\\ ~~~~~~~ \end{bmatrix}$$

## Matrix-Vector Multiplication

We can treat vectors as $n\times 1$ matrices, so multiplying vectors by matrices is also possible (and often very useful!).

**Example:** Compute the product $A\vec{v}$ where $A = \begin{bmatrix} 1 & 0 & -1\\ \color{red}{0} & \color{red}{2} & \color{red}{3}\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} \color{red}{2}\\ \color{red}{-1}\\ \color{red}{3}\end{bmatrix}$

$$A\vec{v} = \begin{bmatrix} -1\\ \color{red}{0\left(2\right) + 2\left(-1\right) + 3\left(3\right)} \end{bmatrix}$$

## Matrix-Vector Multiplication

We can treat vectors as $n\times 1$ matrices, so multiplying vectors by matrices is also possible (and often very useful!).

**Example:** Compute the product $A\vec{v}$ where $A = \begin{bmatrix} 1 & 0 & -1\\ 0 & 2 & 3\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 2\\ -1\\ 3\end{bmatrix}$

$$A\vec{v} = \begin{bmatrix} -1\\ 7 \end{bmatrix}$$

. . .

<br/>
<br/>

Notice that the matrix $A$ transformed the vector $\vec{v}$ from $\mathbb{R}^3$ to $\mathbb{R}^2$ -- the resulting vector is in a completely different space!

## Vector Products Revisited

. . .

We saw vector products in the last discussion but, with our knowledge of matrix multiplication, we can define the *dot product* (or *inner product*) and the *outer product* just as special cases of matrix multiplication.

. . .

Consider two $n\times 1$ vectors $\vec{u} = \begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n\end{bmatrix}$.

+ The *dot product* can be defined by $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$
+ The *outer product* can be defined by $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

. . .

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

+ The *dot product* $\vec{u}\cdot\vec{v}$

:::

:::{.columns width=50%}

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}
\end{align}

:::

:::

:::{.columns width=50%}

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}
\end{align}

:::

:::

:::{.columns width=50%}

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)
\end{align}

:::

:::

:::{.columns width=50%}

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.columns width=50%}

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.column width=50%}

:::{.nonincremental}

+ The *cross product* $\vec{u}\otimes \vec{v}$

:::

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.column width=50%}

:::{.nonincremental}

+ The *cross product* $\vec{u}\otimes \vec{v}$

\begin{align} \vec{u}\otimes\vec{v} &= \vec{u}\vec{v}^T
\end{align}

:::

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.column width=50%}

:::{.nonincremental}

+ The *cross product* $\vec{u}\otimes \vec{v}$

\begin{align} \vec{u}\otimes\vec{v} &= \vec{u}\vec{v}^T\\
&= \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}\begin{bmatrix} 1 & 1 & -3\end{bmatrix}
\end{align}

:::

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.column width=50%}

:::{.nonincremental}

+ The *cross product* $\vec{u}\otimes \vec{v}$

\begin{align} \vec{u}\otimes\vec{v} &= \vec{u}\vec{v}^T\\
&= \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}\begin{bmatrix} 1 & 1 & -3\end{bmatrix}\\
&= \begin{bmatrix} -2\left(1\right) & -2\left(1\right) & -2\left(-3\right)\\ 7\left(1\right) & 7\left(1\right) & 7\left(-3\right)\\ 0\left(1\right) & 0\left(1\right) & 0\left(-3\right)\end{bmatrix}
\end{align}

:::

:::

::::

## Vector Products Revisited

:::::{.columns}

::::{.column width=50%}

:::{.nonincremental}

+ The *dot product* is $\vec{u}\cdot\vec{v} = \vec{u}^T\vec{v}$

:::

::::

::::{.column width=50%}

:::{.nonincremental}

+ The *outer product* is $\vec{u}\otimes \vec{v} = \vec{u}\vec{v}^T$

:::

::::

:::::

**Example:** Given the vectors $\vec{u} = \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}$ and $\vec{v} = \begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}$, compute the dot product and the cross-product.

::::{.columns}

:::{.column width=50%}

:::{.nonincremental}

+ The *dot product* $\vec{u}\cdot\vec{v}$

\begin{align} \vec{u}\cdot \vec{v} & = \vec{u}^T\vec{v}\\
&= \begin{bmatrix} -2 & 7 & 0\end{bmatrix}\begin{bmatrix} 1\\ 1\\ -3\end{bmatrix}\\
&= -2\left(1\right) + 7\left(1\right) + 0\left(-3\right)\\
&= 5
\end{align}

:::

:::

:::{.column width=50%}

:::{.nonincremental}

+ The *cross product* $\vec{u}\otimes \vec{v}$

\begin{align} \vec{u}\otimes\vec{v} &= \vec{u}\vec{v}^T\\
&= \begin{bmatrix} -2\\ 7\\ 0\end{bmatrix}\begin{bmatrix} 1 & 1 & -3\end{bmatrix}\\
&= \begin{bmatrix} -2 & -2 & 6\\ 7 & 7 & -21\\ 0 & 0 & 0\end{bmatrix}
\end{align}

:::

:::

::::

## Preview: Alternative Ways to Think About Matrix-Vector Products

. . . 

Rewrite the matrix $A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots &  \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{bmatrix}$ as $A = \begin{bmatrix} \vec{a_1} & \vec{a_2} & \cdots & \vec{a_n}\end{bmatrix}$

. . .

Where $\vec{a_i} = \begin{bmatrix} a_{1i}\\ a_{2i}\\ \vdots\\ a_{mi}\end{bmatrix}$
    
## Preview: Alternative Ways to Think About Matrix-Vector Products

Consider the product $A\vec{x}$, where $A = \begin{bmatrix} \vec{a_1} & \vec{a_2} & \cdots & \vec{a_n}\end{bmatrix}$ and $\vec{x} = \begin{bmatrix} x_1\\ x_2\\ \vdots\\ x_n\end{bmatrix}$

. . .

::::{.columns}

:::{.column width=50%}

\begin{align} A\vec{x} &= \begin{bmatrix} \vec{a_1} & \vec{a_2} & \cdots & \vec{a_n}\end{bmatrix}\begin{bmatrix} x_1\\ x_2\\ \vdots\\ x_n\end{bmatrix}
\end{align}

:::

:::{.column width=50%}

:::

::::

## Preview: Alternative Ways to Think About Matrix-Vector Products

Consider the product $A\vec{x}$, where $A = \begin{bmatrix} \vec{a_1} & \vec{a_2} & \cdots & \vec{a_n}\end{bmatrix}$ and $\vec{x} = \begin{bmatrix} x_1\\ x_2\\ \vdots\\ x_n\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align} A\vec{x} &= \begin{bmatrix} \vec{a_1} & \vec{a_2} & \cdots & \vec{a_n}\end{bmatrix}\begin{bmatrix} x_1\\ x_2\\ \vdots\\ x_n\end{bmatrix}\\
&= x_1\vec{a_1} + x_2\vec{a_2} + \cdots + x_n\vec{a_n}
\end{align}

:::

:::{.column width=50%}

+ The result is a sum of scalar multiples of the columns of $A$ 

    + This is what we'll eventually call a *linear combination* of $A$'s columns
    + Linear combinations play a very large role in linear algebra
    
:::

::::

## Matrix Division 

. . .

**This Section Intentionally Left Undefined...***

+ As with vectors, there is no division operation with matrices. 
+ This, unfortunately, means that "undoing" matrix multiplication is not as simple as "undoing" scalar multiplication. 
+ This will have several impacts for us moving forward, in particular when we try to solve matrix equations of the form $A\vec{x} = \vec{b}$.

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

. . .

**Identity Matrix:** The $n\times n$ identity matrix, $I_n$, is a matrix such that $I_nA = AI_n = A$. That is, multiplying a matrix $A$ by a compatible identity matrix leaves the matrix $A$ unchanged.

. . .

The form of the $n\times n$ identity matrix is

. . .

$$I_n = \begin{bmatrix} 1 & 0 & \cdots & 0\\ 0 & 1 & \cdots & 0\\ \vdots & \vdots & \ddots & \vdots\\ 0 & 0 & \cdots & 1\end{bmatrix}$$

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

The form of the $n\times n$ **identity matrix** is

<div style="font-size:18pt">

$$I_n = \begin{bmatrix} 1 & 0 & \cdots & 0\\ 0 & 1 & \cdots & 0\\ \vdots & \vdots & \ddots & \vdots\\ 0 & 0 & \cdots & 1\end{bmatrix}$$

</div>

. . .

**Example:** Consider the matrix $A = \begin{bmatrix} 1 & 0 & -2\\ 0 & 3 & 8\\ 3 & 0 & -1\end{bmatrix}$. Compute the following products.

::::{.columns}

:::{.column width=20%}

+ $I_3A$
+ $AI_3$

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

The form of the $n\times n$ **identity matrix** is

<div style="font-size:18pt">

$$I_n = \begin{bmatrix} 1 & 0 & \cdots & 0\\ 0 & 1 & \cdots & 0\\ \vdots & \vdots & \ddots & \vdots\\ 0 & 0 & \cdots & 1\end{bmatrix}$$

</div>

**Example:** Consider the matrix $A = \begin{bmatrix} 1 & 0 & -2\\ 0 & 3 & 8\\ 3 & 0 & -1\end{bmatrix}$. Compute the following products.

::::{.columns}

:::{.column width=20%}

:::{.nonincremental}

+ $I_3A$
+ $AI_3$

:::

:::

:::{.column width=80%}

$$I_3A = \begin{bmatrix} 1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}\begin{bmatrix} 1 & 0 & -2\\ 0 & 3 & 8\\ 3 & 0  & -1\end{bmatrix} = \begin{bmatrix} 1 & 0 & 2\\ 0 & 3 & 8\\ 3 & 0 & -1\end{bmatrix}$$

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

+ We mentioned that matrix division does not exist
+ Some matrices have corresponding inverse matrices, though

. . .

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

. . .

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

$$AB = \begin{bmatrix}7 & -3\\ -2 & 1\end{bmatrix}\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$$

:::

:::{.column width=50%}

$$BA = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix}7 & -3\\ -2 & 1\end{bmatrix}$$

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix}\color{red}{7} & \color{red}{-3}\\ -2 & 1\end{bmatrix}\begin{bmatrix} \color{red}{1} & 3\\ \color{red}{2} & 7\end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} \color{red}{1} & \color{red}{3}\\ 2 & 7\end{bmatrix}\begin{bmatrix}\color{red}{7} & -3\\ \color{red}{-2} & 1\end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix}\color{red}{7} & \color{red}{-3}\\ -2 & 1\end{bmatrix}\begin{bmatrix} \color{red}{1} & 3\\ \color{red}{2} & 7\end{bmatrix}\\ 
&= \begin{bmatrix} \color{red}{7\left(1\right) + \left(-3\right)\left(2\right)} & ~~~~~~~~~~~~\\
 & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} \color{red}{1} & \color{red}{3}\\ 2 & 7\end{bmatrix}\begin{bmatrix}\color{red}{7} & -3\\ \color{red}{-2} & 1\end{bmatrix}\\
&= \begin{bmatrix} \color{red}{1\left(7\right) + 3\left(-2\right)} & ~~~~~~~~~~~~~~~\\
 & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix}\color{red}{7} & \color{red}{-3}\\ -2 & 1\end{bmatrix}\begin{bmatrix} 1 & \color{red}{3}\\ 2 & \color{red}{7}\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & ~~~~~~~~~~~~\\
 & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} \color{red}{1} & \color{red}{3}\\ 2 & 7\end{bmatrix}\begin{bmatrix} 7 & \color{red}{-3}\\ -2 & \color{red}{1}\end{bmatrix}\\
&= \begin{bmatrix} 1 & ~~~~~~~~~~~~~~~\\
 & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix}\color{red}{7} & \color{red}{-3}\\ -2 & 1\end{bmatrix}\begin{bmatrix} 1 & \color{red}{3}\\ 2 & \color{red}{7}\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & \color{red}{7\left(3\right) + \left(-3\right)\left(7\right)}\\
 & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} \color{red}{1} & \color{red}{3}\\ 2 & 7\end{bmatrix}\begin{bmatrix} 7 & \color{red}{-3}\\ -2 & \color{red}{1}\end{bmatrix}\\
&= \begin{bmatrix} 1 & \color{red}{1\left(-3\right) + 3\left(1\right)}\\
 & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ \color{red}{-2} & \color{red}{1}\end{bmatrix}\begin{bmatrix} \color{red}{1} & 3\\ \color{red}{2} & 7\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
 & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ \color{red}{2} & \color{red}{7}\end{bmatrix}\begin{bmatrix} \color{red}{7} & -3\\ \color{red}{-2} & 1\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
 & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ \color{red}{-2} & \color{red}{1}\end{bmatrix}\begin{bmatrix} \color{red}{1} & 3\\ \color{red}{2} & 7\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
\color{red}{-2\left(1\right) + 1\left(2\right)} & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ \color{red}{2} & \color{red}{7}\end{bmatrix}\begin{bmatrix} \color{red}{7} & -3\\ \color{red}{-2} & 1\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
\color{red}{2\left(7\right) + 7\left(-2\right)} & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ \color{red}{-2} & \color{red}{1}\end{bmatrix}\begin{bmatrix} 1 & \color{red}{3}\\ 2 & \color{red}{7}\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
0 & \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ \color{red}{2} & \color{red}{7}\end{bmatrix}\begin{bmatrix} 7 & \color{red}{-3}\\ -2 & \color{red}{1}\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
0 & \end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ \color{red}{-2} & \color{red}{1}\end{bmatrix}\begin{bmatrix} 1 & \color{red}{3}\\ 2 & \color{red}{7}\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
0 & \color{red}{-2\left(3\right) + 1\left(7\right)}\end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ \color{red}{2} & \color{red}{7}\end{bmatrix}\begin{bmatrix} 7 & \color{red}{-3}\\ -2 & \color{red}{1}\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
0 & \color{red}{2\left(-3\right) + 7\left(1\right)}\end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
0 & 1\end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
0 & 1\end{bmatrix}
\end{align}

:::

::::

## Special Matrices

There are several special matrices that we'll encounter throughout linear algebra. We'll introduce two of those now.

**Inverse Matrices:** For an $n\times n$ matrix $A$, there *may* exist an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, we call $B$ the *inverse* of $A$ and write $B = A^{-1}$.

**Example:** Show that the matrix $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$ by computing $AB$ and $BA$.

::::{.columns}

:::{.column width=50%}

\begin{align} AB &= \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\\ 
&= \begin{bmatrix} 1 & 0\\
0 & 1\end{bmatrix} ~~~~\checkmark\end{align}

:::

:::{.column width=50%}

\begin{align} BA &= \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\\
&= \begin{bmatrix} 1 & 0\\
0 & 1\end{bmatrix} ~~~~\checkmark
\end{align}

:::

::::

## Special Matrices

<div style="font-size:18pt">

**Example:** Knowing that $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$, use multiplication by $B$ to solve the matrix equation $\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} = \begin{bmatrix} 5\\ -8\end{bmatrix}$

</div>

. . .

<div style="font-size:18pt">

\begin{align} \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \begin{bmatrix} 5\\ -8\end{bmatrix}
\end{align}

</div>

## Special Matrices

<div style="font-size:18pt">

**Example:** Knowing that $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$, use multiplication by $B$ to solve the matrix equation $\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} = \begin{bmatrix} 5\\ -8\end{bmatrix}$

\begin{align} \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \begin{bmatrix} 5\\ -8\end{bmatrix}\\
 \implies \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 5\\ -8\end{bmatrix}
\end{align}

</div>

## Special Matrices

<div style="font-size:18pt">

**Example:** Knowing that $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$, use multiplication by $B$ to solve the matrix equation $\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} = \begin{bmatrix} 5\\ -8\end{bmatrix}$

\begin{align} \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \begin{bmatrix} 5\\ -8\end{bmatrix}\\
 \implies \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 5\\ -8\end{bmatrix}\\
\implies \color{red}{I}\vec{x} &= \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix} 5\\ -8\end{bmatrix}
\end{align}

</div>

## Special Matrices

<div style="font-size:18pt">

**Example:** Knowing that $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$, use multiplication by $B$ to solve the matrix equation $\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} = \begin{bmatrix} 5\\ -8\end{bmatrix}$

\begin{align} \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \begin{bmatrix} 5\\ -8\end{bmatrix}\\
 \implies \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 5\\ -8\end{bmatrix}\\
\implies \color{red}{I}\vec{x} &= \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix} 5\\ -8\end{bmatrix}\\
\implies \vec{x} &= \begin{bmatrix} 1\left(5\right) + 3\left(-8\right)\\ 2\left(5\right) + 7\left(-8\right)\end{bmatrix}
\end{align}

</div>

## Special Matrices

<div style="font-size:18pt">

**Example:** Knowing that $B = \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}$ is the inverse of the matrix $A = \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}$, use multiplication by $B$ to solve the matrix equation $\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} = \begin{bmatrix} 5\\ -8\end{bmatrix}$

\begin{align} \begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \begin{bmatrix} 5\\ -8\end{bmatrix}\\
 \implies \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 7 & -3\\ -2 & 1\end{bmatrix}\vec{x} &= \color{red}{\begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}}\begin{bmatrix} 5\\ -8\end{bmatrix}\\
\implies \color{red}{I}\vec{x} &= \begin{bmatrix} 1 & 3\\ 2 & 7\end{bmatrix}\begin{bmatrix} 5\\ -8\end{bmatrix}\\
\implies \vec{x} &= \begin{bmatrix} 1\left(5\right) + 3\left(-8\right)\\ 2\left(5\right) + 7\left(-8\right)\end{bmatrix}\\
\implies \vec{x} &= \begin{bmatrix} -19\\ -46\end{bmatrix}
\end{align}

</div>

## Summary

In this slide deck, you've seen and practiced...

+ recognizing the dimension of a matrix
+ multiplying a matrix by a scalar
+ adding and subtracting compatible matrices
+ multiplying matrices and vectors

    + an alternative, and useful, way to think about matrix-vector products
+ identifying and using an identity matrix
+ verifying two matrices are inverses of one another
+ using the inverse of a matrix to solve a matrix equation

## Homework

<br/>
<br/>
<br/>

. . .

<center>

$$\Huge{\text{Finish Homework 1}}$$ 
$$\Huge{\text{on MyOpenMath}}$$

</center>

## Next Time...

<br/>
<br/>
<br/>

. . .

<center>

$\Huge{\text{Finding Solutions to Linear Systems}}$

</center>


