---
title: "MAT 350: Row Reduction Workshop"
author: Dr. Gilbert
format: 
  revealjs:
    smaller: true
date: today
date-format: long
theme: serif
incremental: true
---

```{r global-options, include=FALSE}
library(tidyverse)
library(reticulate)

theme_set(theme_bw(base_size = 20))
```

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

```{css}
code.sourceCode {
  font-size: 1.3em;
  /* or try font-size: xx-large; */
}

a {
  color: purple;
}

a:link {
  color: purple;
}

a:visited {
  color: purple;
}
```

## Reminders and Today's Goal

+ The purpose of today's class meeting is simple -- build confidence with row reduction. 
+ As mentioned previously, you'll have a row reduction ***Gateway Exam*** in MAT350 worth 15% of your overall course grade that you'll need to pass before the end of the semester. 
+ You'll be able to retake the Gateway Exam multiple times to show mastery. 

    + **Limits:** Once per week until the Thanksgiving Break and then twice per week afterwards
+ Each Gateway Exam will consist of four matrices for you to reduce within a strict 20-minute time limit. 
+ You'll need to correctly reduce at least three of the matrices to their ***reduced row echelon*** form in order to pass.

. . .

**First Attempt:** Your first attempt at the Gateway Exam will take place at the end of this class meeting. Prior to that, we'll take time to practice.

## Completed Examples: Example \#1

**Example:** Reduce the matrix below to its corresponding ***reduced row echeclon*** form.

. . . 

$$A = \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix}$$

. . .

\begin{align} \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix} 
\end{align}

## Completed Examples: Example \#1

**Example:** Reduce the matrix below to its corresponding ***reduced row echeclon*** form.

$$A = \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix}$$

\begin{align} \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix} &\stackrel{R_2 \leftarrow R_2 + 3R_1}{\longrightarrow} \begin{bmatrix} 1 & 4\\ 0 & 20\end{bmatrix}
\end{align}

## Completed Examples: Example \#1

**Example:** Reduce the matrix below to its corresponding ***reduced row echeclon*** form.

$$A = \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix}$$

\begin{align} \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix} &\stackrel{R_2 \leftarrow R_2 + 3R_1}{\longrightarrow} \begin{bmatrix} 1 & 4\\ 0 & 20\end{bmatrix}\\
&\stackrel{R_2 \leftarrow \frac{1}{20}R_2}{\longrightarrow} \begin{bmatrix} 1 & 4\\ 0 & 1\end{bmatrix}
\end{align}

## Completed Examples: Example \#1

**Example:** Reduce the matrix below to its corresponding ***reduced row echeclon*** form.

$$A = \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix}$$

\begin{align} \begin{bmatrix} 1 & 4\\ -3 & 8\end{bmatrix} &\stackrel{R_2 \leftarrow R_2 + 3R_1}{\longrightarrow} \begin{bmatrix} 1 & 4\\ 0 & 20\end{bmatrix}\\
&\stackrel{R_2 \leftarrow \frac{1}{20}R_2}{\longrightarrow} \begin{bmatrix} 1 & 4\\ 0 & 1\end{bmatrix}\\
&\stackrel{R_1 \leftarrow R_1 + (-4)R_2}{\longrightarrow}\begin{bmatrix} 1 & 0\\ 0 & 1\end{bmatrix}~~\blacktriangledown
\end{align}

. . .

This was a square matrix with a pivot in every row and every column.

## Completed Examples: Example \#2

. . .

**Example:** $C = \begin{bmatrix} 1 & 2 & 3 & 4 & 5\\
2 & 4 & 6 & 8 & 10\\
0 & 1 & 0 & -1 & -2\end{bmatrix}$

. . .

\begin{align}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 2 & 4 & 6 & 8 & 10\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix}
\end{align}

## Completed Examples: Example \#2

**Example:** $C = \begin{bmatrix} 1 & 2 & 3 & 4 & 5\\
2 & 4 & 6 & 8 & 10\\
0 & 1 & 0 & -1 & -2\end{bmatrix}$

\begin{align}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 2 & 4 & 6 & 8 & 10\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix}
&\stackrel{R_2 \leftarrow R_2 + (-2)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 0 & 0 & 0 & 0 & 0\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix}
\end{align}

## Completed Examples: Example \#2

**Example:** $C = \begin{bmatrix} 1 & 2 & 3 & 4 & 5\\
2 & 4 & 6 & 8 & 10\\
0 & 1 & 0 & -1 & -2\end{bmatrix}$

\begin{align}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 2 & 4 & 6 & 8 & 10\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix}
&\stackrel{R_2 \leftarrow R_2 + (-2)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 0 & 0 & 0 & 0 & 0\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix} \\
&\stackrel{R_3 \leftrightarrow R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 0 & 1 & 0 & -1 & -2\\ 0 & 0 & 0 & 0 & 0 \end{bmatrix}
\end{align}

## Completed Examples: Example \#2

**Example:** $C = \begin{bmatrix} 1 & 2 & 3 & 4 & 5\\
2 & 4 & 6 & 8 & 10\\
0 & 1 & 0 & -1 & -2\end{bmatrix}$

\begin{align}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 2 & 4 & 6 & 8 & 10\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix}
&\stackrel{R_2 \leftarrow R_2 + (-2)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 0 & 0 & 0 & 0 & 0\\ 0 & 1 & 0 & -1 & -2 \end{bmatrix} \\
&\stackrel{R_3 \leftrightarrow R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 3 & 4 & 5\\ 0 & 1 & 0 & -1 & -2\\ 0 & 0 & 0 & 0 & 0 \end{bmatrix} \\
&\stackrel{R_1 \leftarrow R_1 + (-2)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 0 & 3 & 6 & 9\\ 0 & 1 & 0 & -1 & -2\\ 0 & 0 & 0 & 0 & 0 \end{bmatrix}
~~\blacktriangledown
\end{align}

. . .

This was a rectangular matrix with a pivots missing in both rows and columns.

## Completed Examples: Example \#3

. . .

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

. . .

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\stackrel{R_1 \leftarrow \frac{1}{2} R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\stackrel{R_1 \leftarrow \frac{1}{2} R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix} \\
&\stackrel{R_2 \leftarrow R_2 + (-1)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 3 & 9 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\stackrel{R_1 \leftarrow \frac{1}{2} R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix} \\
&\stackrel{R_2 \leftarrow R_2 + (-1)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 3 & 9 & 1 \end{bmatrix} \\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_1}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}


:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}


:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & -2 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & -2 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow \left(-\frac{1}{2}\right) R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}



:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & -2 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow \left(-\frac{1}{2}\right) R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} &\stackrel{R_2 \leftarrow R_2 + (-2)R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & -2 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow \left(-\frac{1}{2}\right) R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} &\stackrel{R_2 \leftarrow R_2 + (-2)R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}\\
&\stackrel{R_1 \leftarrow R_1 + R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

::::

## Completed Examples: Example \#3

**Example:** $B = \begin{bmatrix} 2 & 4 & -2\\
1 & 3 & 1\\
3 & 9 & 1\end{bmatrix}$

::::{.columns}

:::{.column width=50%}

\begin{align}
\begin{bmatrix} 2 & 4 & -2\\ 1 & 3 & 1\\ 3 & 9 & 1 \end{bmatrix}
&\sim \begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 3 & 4 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow R_3 + (-3)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & -2 \end{bmatrix}\\
&\stackrel{R_3 \leftarrow \left(-\frac{1}{2}\right) R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 2\\ 0 & 0 & 1 \end{bmatrix}
\end{align}

:::

:::{.column width=50%}

\begin{align} &\stackrel{R_2 \leftarrow R_2 + (-2)R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & -1\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}\\
&\stackrel{R_1 \leftarrow R_1 + R_3}{\longrightarrow}
\begin{bmatrix} 1 & 2 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix} \\
&\stackrel{R_1 \leftarrow R_1 + (-2)R_2}{\longrightarrow}
\begin{bmatrix} 1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1 \end{bmatrix}~~\blacktriangledown
\end{align}

:::

::::

. . . 

Another square matrix with pivots in every row and column.

## Examples to Try

+ The following slides include examples for you to try on your own. 
+ The groups are loosely arranged by difficulty of the row reduction tasks. 
+ For each of the presented matrices, perform row reduction operations to convert the matrix into its equivalent reduced row echelon form.

## Examples to Try: Group \#1

i) $A_1 = \begin{bmatrix}1 & 2\\ 0 & 3\end{bmatrix}$
ii) $A_2 = \begin{bmatrix} 1 & 0\\ 0 & 1\\ 2 & 3\end{bmatrix}$
iii) $A_3 = \begin{bmatrix} 1 & 2 & 3\\ 0 & 1 & 4\end{bmatrix}$

## Examples to Try: Group \#2

iv) $B_1 = \begin{bmatrix} 2 & 4 & -2\\ -1 & -2 & 1\\ 1 & 1 & 0\end{bmatrix}$
v) $B_2 = \begin{bmatrix} 1 & 2 & 1 & 0\\
2 & 4 & 3 & 1\\
1 & 1 & 2 & 3\end{bmatrix}$
vi) $B_3 = \begin{bmatrix} 1 & 2 & 3\\
0 & 1 & 4\\
0 & 0 & 1\\
0 & 0 & 0\end{bmatrix}$

## Examples to Try: Group \#3

vii) $C_1 = \begin{bmatrix} 0 & 2 & 4 & 6\\
1 & 3 & 1 & 5\\
2 & 6 & 2 & 10\\
3 & 1 & 1 & 4\end{bmatrix}$
viii) $C_2 = \begin{bmatrix} 1 & 1 & 1\\
2 & 2 & 2\\
1 & 0 & 1\\
0 & 1 & 2\\
3 & 3 & 3\end{bmatrix}$
ix) $C_3 = \begin{bmatrix} 1 & 2 & 0 & 3 & 1\\
2 & 4 & -1 & 6 & 2\\
-1 & -2 & 1 & -3 & 0\\
0 & 0 & 2 & 1 & 3\end{bmatrix}$

## Homework

<br/>
<br/>
<br/>

. . .

<center>

$$\Huge{\text{Finish Homework 3}}$$ 
$$\Huge{\text{on MyOpenMath}}$$

</center>

## Next Time...

<br/>
<br/>
<br/>

. . .

<center>

$\Huge{\text{Vectors and Linear Combinations}}$

</center>


